include:
  - .gitlab/ci/*.gitlab-ci.yml

stages:
  - build
  - deploy
  - rollback


build-prod:
  stage: build
  extends: .build_template
  variables:
    ENV_TAG: latest
    DOCKERFILE: Dockerfile
  only:
    - master


deploy-prod:
  stage: deploy
  extends: .deploy_template
  variables:
    NAMESPACE: xlogistics
    VALUES_FILE: .helm/values-prod.yml
    K8SCONFIGJSON: $FURGO_KUBECONFIG
  only:
    - master

rollback-prod:
  stage: rollback
  extends: .rollback_template
  variables:
    NAMESPACE: xlogistics
    K8SCONFIGJSON: $FURGO_KUBECONFIG
  when: manual
