export const countries = [
  {
    name_uz: "Kazakhstan",
    name_ru: "Казахстан",
    code: "KZ",
    vehicle_plate_regex: "^[A-Z]{1}\\d{3}[A-Z]{2}\\d{2,3}$",
  },
  {
    name_uz: "Kyrgyzstan",
    name_ru: "Кыргызстан",
    code: "KG",
    vehicle_plate_regex: "^[0-9]{2}\\s[\u0410-\u042F]{2}\\s[0-9]{4}$",
  },
  {
    name_uz: "Tajikistan",
    name_ru: "Таджикистан",
    code: "TJ",
    vehicle_plate_regex: "^[0-9]{2}\\s[\u0410-\u042F]{2}\\s[0-9]{4}$",
  },
  {
    name_uz: "Turkmenistan",
    name_ru: "Туркменистан",
    code: "TM",
    vehicle_plate_regex: "^[0-9]{2}\\s[\u0410-\u042F]{2}\\s[0-9]{4}$",
  },
  {
    name_uz: "Uzbekistan",
    name_ru: "Узбекистан",
    code: "UZ",
    vehicle_plate_regex: "^[0-9]{2}[A-Z]{2}[0-9]{3}[A-Z]{1}$",
  },
  {
    name_uz: "Russia",
    name_ru: "Россия",
    code: "RU",
    vehicle_plate_regex:
      "^[\u0410-\u0412\u0415\u041a\u041c\u041d\u041e\u0420\u0421\u0422\u0423\u0425]{1}\\d{3}[\u0410-\u0412\u0415\u041a\u041c\u041d\u041e\u0420\u0421\u0422\u0423\u0425]{2}\\d{2,3}$",
  },
  {
    name_uz: "Armenia",
    name_ru: "Армения",
    code: "AM",
    vehicle_plate_regex: "^[0-9]{2}[A-Z]{2}[0-9]{3}$",
  },
  {
    name_uz: "Azerbaijan",
    name_ru: "Азербайджан",
    code: "AZ",
    vehicle_plate_regex: "^[0-9]{2}-[A-Z]{2}-[0-9]{3}$",
  },
  {
    name_uz: "Georgia",
    name_ru: "Грузия",
    code: "GE",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}[A-Z]{2}$",
  },
  {
    name_uz: "Ukraine",
    name_ru: "Украина",
    code: "UA",
    vehicle_plate_regex: "^[A-Z]{2}\\d{4}[A-Z]{2}$",
  },
  {
    name_uz: "Belarus",
    name_ru: "Беларусь",
    code: "BY",
    vehicle_plate_regex: "^[0-9]{4}\\s[\u0410-\u042F]{2}-[0-9]{1}$",
  },
  {
    name_uz: "Moldova",
    name_ru: "Молдова",
    code: "MD",
    vehicle_plate_regex: "^[A-Z]{3}\\d{3}$",
  },
  {
    name_uz: "Albania",
    name_ru: "Албания",
    code: "AL",
    vehicle_plate_regex: "^[A-Z]{2}\\d{4}[A-Z]{1}$",
  },
  {
    name_uz: "Andorra",
    name_ru: "Андорра",
    code: "AD",
    vehicle_plate_regex: "^AD\\d{4}$",
  },
  {
    name_uz: "Austria",
    name_ru: "Австрия",
    code: "AT",
    vehicle_plate_regex: "^[A-Z]{1,3}\\d{1,4}[A-Z]{1,2}$",
  },
  {
    name_uz: "Belgium",
    name_ru: "Бельгия",
    code: "BE",
    vehicle_plate_regex: "^[1-9]{1}[A-Z]{3}\\d{3}$",
  },
  {
    name_uz: "Bosnia and Herzegovina",
    name_ru: "Босния и Герцеговина",
    code: "BA",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}[A-Z]{2}$",
  },
  {
    name_uz: "Bulgaria",
    name_ru: "Болгария",
    code: "BG",
    vehicle_plate_regex: "^[A-Z]{1,2}\\d{4}[A-Z]{1,2}$",
  },
  {
    name_uz: "Croatia",
    name_ru: "Хорватия",
    code: "HR",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}-\\d{2}$",
  },
  {
    name_uz: "Cyprus",
    name_ru: "Кипр",
    code: "CY",
    vehicle_plate_regex: "^[A-Z]{3}\\d{3}$",
  },
  {
    name_uz: "Czech Republic",
    name_ru: "Чехия",
    code: "CZ",
    vehicle_plate_regex: "^[A-Z]{2}-\\d{5}$",
  },
  {
    name_uz: "Denmark",
    name_ru: "Дания",
    code: "DK",
    vehicle_plate_regex: "^[A-Z]{2}\\d{5}$",
  },
  {
    name_uz: "Estonia",
    name_ru: "Эстония",
    code: "EE",
    vehicle_plate_regex: "^[A-Z]{3}-\\d{3}$",
  },
  {
    name_uz: "Finland",
    name_ru: "Финляндия",
    code: "FI",
    vehicle_plate_regex: "^[A-Z]{3}-\\d{3}$",
  },
  {
    name_uz: "France",
    name_ru: "Франция",
    code: "FR",
    vehicle_plate_regex: "^[A-Z]{2}-\\d{3}-[A-Z]{2}$",
  },
  {
    name_uz: "Germany",
    name_ru: "Германия",
    code: "DE",
    vehicle_plate_regex: "^[A-Z]{1,3}-[A-Z]{1,2}\\d{1,4}$",
  },
  {
    name_uz: "Greece",
    name_ru: "Греция",
    code: "GR",
    vehicle_plate_regex: "^[A-Z]{3}-\\d{4}$",
  },
  {
    name_uz: "Hungary",
    name_ru: "Венгрия",
    code: "HU",
    vehicle_plate_regex: "^[A-Z]{3}-\\d{3}$",
  },
  {
    name_uz: "Iceland",
    name_ru: "Исландия",
    code: "IS",
    vehicle_plate_regex: "^[A-Z]{1,2}\\d{3}$",
  },
  {
    name_uz: "Ireland",
    name_ru: "Ирландия",
    code: "IE",
    vehicle_plate_regex: "^d{2}-[A-Z]{1,2}-\\d{1,5}$",
  },
  {
    name_uz: "Italy",
    name_ru: "Италия",
    code: "IT",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}[A-Z]{2}$",
  },
  {
    name_uz: "Latvia",
    name_ru: "Латвия",
    code: "LV",
    vehicle_plate_regex: "^[A-Z]{2}-\\d{4}$",
  },
  {
    name_uz: "Liechtenstein",
    name_ru: "Лихтенштейн",
    code: "LI",
    vehicle_plate_regex: "^FL-\\d{1,5}$",
  },
  {
    name_uz: "Lithuania",
    name_ru: "Литва",
    code: "LT",
    vehicle_plate_regex: "^[A-Z]{3}\\d{3}$",
  },
  {
    name_uz: "Luxembourg",
    name_ru: "Люксембург",
    code: "LU",
    vehicle_plate_regex: "^[A-Z]{2}-\\d{5}$",
  },
  {
    name_uz: "Malta",
    name_ru: "Мальта",
    code: "MT",
    vehicle_plate_regex: "^[A-Z]{3}\\d{4}$",
  },
  {
    name_uz: "Netherlands",
    name_ru: "Нидерланды",
    code: "NL",
    vehicle_plate_regex: "^[A-Z]{1,2}\\d{2,3}[A-Z]{1,2}$",
  },
  {
    name_uz: "North Macedonia",
    name_ru: "Северная Македония",
    code: "MK",
    vehicle_plate_regex: "^[A-Z]{2}\\d{1,4}[A-Z]{1,2}$",
  },
  {
    name_uz: "Norway",
    name_ru: "Норвегия",
    code: "NO",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3,4}$",
  },
  {
    name_uz: "Poland",
    name_ru: "Польша",
    code: "PL",
    vehicle_plate_regex: "^[A-Z]{2}\\d{4}[A-Z]{1}$",
  },
  {
    name_uz: "Portugal",
    name_ru: "Португалия",
    code: "PT",
    vehicle_plate_regex: "^[A-Z]{2}\\d{2}-\\d{2}$",
  },
  {
    name_uz: "Romania",
    name_ru: "Румыния",
    code: "RO",
    vehicle_plate_regex: "^[B-DFGHJKLMNPRSTVWXYZ]{2}\\d{2,4}[A-Z]{2}$",
  },
  {
    name_uz: "San Marino",
    name_ru: "Сан-Марино",
    code: "SM",
    vehicle_plate_regex: "^[A-Z]{1,2}\\d{1,5}$",
  },
  {
    name_uz: "Serbia",
    name_ru: "Сербия",
    code: "RS",
    vehicle_plate_regex: "^[A-Z]{2}\\d{1,4}$",
  },
  {
    name_uz: "Slovakia",
    name_ru: "Словакия",
    code: "SK",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}[A-Z]{1}$",
  },
  {
    name_uz: "Slovenia",
    name_ru: "Словения",
    code: "SI",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}[A-Z]{1,2}$",
  },
  {
    name_uz: "Spain",
    name_ru: "Испания",
    code: "ES",
    vehicle_plate_regex: "^[A-Z]{4}\\d{3}$",
  },
  {
    name_uz: "Sweden",
    name_ru: "Швеция",
    code: "SE",
    vehicle_plate_regex: "^[A-Z]{3}\\d{3}$",
  },
  {
    name_uz: "Switzerland",
    name_ru: "Швейцария",
    code: "CH",
    vehicle_plate_regex: "^[A-Z]{2}\\d{1,3}$",
  },
  {
    name_uz: "Turkey",
    name_ru: "Турция",
    code: "TR",
    vehicle_plate_regex: "^[0-9]{2}[A-Z]{1,2}\\d{1,4}$",
  },
  {
    name_uz: "United Kingdom",
    name_ru: "Великобритания",
    code: "GB",
    vehicle_plate_regex: "^[A-Z]{2}\\d{1,4}[A-Z]{1}$",
  },
  {
    name_uz: "Vatican City",
    name_ru: "Ватикан",
    code: "VA",
    vehicle_plate_regex: "^[A-Z]{1,2}\\d{1,5}$",
  },
  {
    name_uz: "China",
    name_ru: "Китай",
    code: "CN",
    vehicle_plate_regex: "^[A-Z]{1}[A-Z\\d]{5}$",
  },
  {
    name_uz: "India",
    name_ru: "Индия",
    code: "IN",
    vehicle_plate_regex: "^[A-Z]{2}\\d{4}$",
  },
  {
    name_uz: "Monaco",
    name_ru: "Монако",
    code: "MC",
    vehicle_plate_regex: "^[A-Z]{1,3}\\d{1,5}$",
  },
];
