export const countries = [
  {
    name_uz: "Kazakhstan",
    name_ru: "Казахстан",
    name_zh: "哈萨克斯坦",
    name_tr: "Kazakistan",
    name_en: "Kazakhstan",
    code: "KZ",
    vehicle_plate_regex: "^[A-Z]{1}\\d{3}[A-Z]{2}\\d{2,3}$",
  },
  {
    name_uz: "Kyrgyzstan",
    name_ru: "Кыргызстан",
    name_zh: "吉尔吉斯斯坦",
    name_tr: "Kırgızistan",
    name_en: "Kyrgyzstan",
    code: "KG",
    vehicle_plate_regex: "^[0-9]{2}\\s[\u0410-\u042F]{2}\\s[0-9]{4}$",
  },
  {
    name_uz: "Tajikistan",
    name_ru: "Таджикистан",
    name_zh: "塔吉克斯坦",
    name_tr: "Tacikistan",
    name_en: "Tajikistan",
    code: "TJ",
    vehicle_plate_regex: "^[0-9]{2}\\s[\u0410-\u042F]{2}\\s[0-9]{4}$",
  },
  {
    name_uz: "Turkmenistan",
    name_ru: "Туркменистан",
    name_zh: "土库曼斯坦",
    name_tr: "Türkmenistan",
    name_en: "Turkmenistan",
    code: "TM",
    vehicle_plate_regex: "^[0-9]{2}\\s[\u0410-\u042F]{2}\\s[0-9]{4}$",
  },
  {
    name_uz: "Uzbekistan",
    name_ru: "Узбекистан",
    name_zh: "乌兹别克斯坦",
    name_tr: "Özbekistan",
    name_en: "Uzbekistan",
    code: "UZ",
    vehicle_plate_regex: "^[0-9]{2}[A-Z]{2}[0-9]{3}[A-Z]{1}$",
  },
  {
    name_uz: "Russia",
    name_ru: "Россия",
    name_zh: "俄罗斯",
    name_tr: "Rusya",
    name_en: "Russia",
    code: "RU",
    vehicle_plate_regex:
      "^[\u0410-\u0412\u0415\u041A\u041C\u041D\u041E\u0420\u0421\u0422\u0423\u0425]{1}\\d{3}[\u0410-\u0412\u0415\u041A\u041C\u041D\u041E\u0420\u0421\u0422\u0423\u0425]{2}\\d{2,3}$",
  },
  {
    name_uz: "Armenia",
    name_ru: "Армения",
    name_zh: "亚美尼亚",
    name_tr: "Ermenistan",
    name_en: "Armenia",
    code: "AM",
    vehicle_plate_regex: "^[0-9]{2}[A-Z]{2}[0-9]{3}$",
  },
  {
    name_uz: "Azerbaijan",
    name_ru: "Азербайджан",
    name_zh: "阿塞拜疆",
    name_tr: "Azerbaycan",
    name_en: "Azerbaijan",
    code: "AZ",
    vehicle_plate_regex: "^[0-9]{2}-[A-Z]{2}-[0-9]{3}$",
  },
  {
    name_uz: "Georgia",
    name_ru: "Грузия",
    name_zh: "格鲁吉亚",
    name_tr: "Gürcistan",
    name_en: "Georgia",
    code: "GE",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}[A-Z]{2}$",
  },
  {
    name_uz: "Ukraine",
    name_ru: "Украина",
    name_zh: "乌克兰",
    name_tr: "Ukrayna",
    name_en: "Ukraine",
    code: "UA",
    vehicle_plate_regex: "^[A-Z]{2}\\d{4}[A-Z]{2}$",
  },
  {
    name_uz: "Belarus",
    name_ru: "Беларусь",
    name_zh: "白俄罗斯",
    name_tr: "Belarus",
    name_en: "Belarus",
    code: "BY",
    vehicle_plate_regex: "^[0-9]{4}\\s[\u0410-\u042F]{2}-[0-9]{1}$",
  },
  {
    name_uz: "Moldova",
    name_ru: "Молдова",
    name_zh: "摩尔多瓦",
    name_tr: "Moldova",
    name_en: "Moldova",
    code: "MD",
    vehicle_plate_regex: "^[A-Z]{3}\\d{3}$",
  },
  {
    name_uz: "Albania",
    name_ru: "Албания",
    name_zh: "阿尔巴尼亚",
    name_tr: "Arnavutluk",
    name_en: "Albania",
    code: "AL",
    vehicle_plate_regex: "^[A-Z]{2}\\d{4}[A-Z]{1}$",
  },
  {
    name_uz: "Andorra",
    name_ru: "Андорра",
    name_zh: "安道尔",
    name_tr: "Andorra",
    name_en: "Andorra",
    code: "AD",
    vehicle_plate_regex: "^AD\\d{4}$",
  },
  {
    name_uz: "Austria",
    name_ru: "Австрия",
    name_zh: "奥地利",
    name_tr: "Avusturya",
    name_en: "Austria",
    code: "AT",
    vehicle_plate_regex: "^[A-Z]{1,3}\\d{1,4}[A-Z]{1,2}$",
  },
  {
    name_uz: "Belgium",
    name_ru: "Бельгия",
    name_zh: "比利时",
    name_tr: "Belçika",
    name_en: "Belgium",
    code: "BE",
    vehicle_plate_regex: "^[1-9]{1}[A-Z]{3}\\d{3}$",
  },
  {
    name_uz: "Bosnia and Herzegovina",
    name_ru: "Босния и Герцеговина",
    name_zh: "波斯尼亚和黑塞哥维那",
    name_tr: "Bosna Hersek",
    name_en: "Bosnia and Herzegovina",
    code: "BA",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}[A-Z]{2}$",
  },
  {
    name_uz: "Bulgaria",
    name_ru: "Болгария",
    name_zh: "保加利亚",
    name_tr: "Bulgaristan",
    name_en: "Bulgaria",
    code: "BG",
    vehicle_plate_regex: "^[A-Z]{1,2}\\d{4}[A-Z]{1,2}$",
  },

  {
    name_uz: "Croatia",
    name_ru: "Хорватия",
    name_tr: "Hırvatistan",
    name_zh: "克罗地亚",
    name_en: "Croatia",
    code: "HR",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}-\\d{2}$",
  },
  {
    name_uz: "Cyprus",
    name_ru: "Кипр",
    name_tr: "Kıbrıs",
    name_zh: "塞浦路斯",
    name_en: "Cyprus",
    code: "CY",
    vehicle_plate_regex: "^[A-Z]{3}\\d{3}$",
  },
  {
    name_uz: "Czech Republic",
    name_ru: "Чехия",
    name_tr: "Çek Cumhuriyeti",
    name_zh: "捷克共和国",
    name_en: "Czech Republic",
    code: "CZ",
    vehicle_plate_regex: "^[A-Z]{2}-\\d{5}$",
  },
  {
    name_uz: "Denmark",
    name_ru: "Дания",
    name_tr: "Danimarka",
    name_zh: "丹麦",
    name_en: "Denmark",
    code: "DK",
    vehicle_plate_regex: "^[A-Z]{2}\\d{5}$",
  },
  {
    name_uz: "Estonia",
    name_ru: "Эстония",
    name_tr: "Estonya",
    name_zh: "爱沙尼亚",
    name_en: "Estonia",
    code: "EE",
    vehicle_plate_regex: "^[A-Z]{3}-\\d{3}$",
  },
  {
    name_uz: "Finland",
    name_ru: "Финляндия",
    name_tr: "Finlandiya",
    name_zh: "芬兰",
    name_en: "Finland",
    code: "FI",
    vehicle_plate_regex: "^[A-Z]{3}-\\d{3}$",
  },
  {
    name_uz: "France",
    name_ru: "Франция",
    name_tr: "Fransa",
    name_zh: "法国",
    name_en: "France",
    code: "FR",
    vehicle_plate_regex: "^[A-Z]{2}-\\d{3}-[A-Z]{2}$",
  },
  {
    name_uz: "Germany",
    name_ru: "Германия",
    name_tr: "Almanya",
    name_zh: "德国",
    name_en: "Germany",
    code: "DE",
    vehicle_plate_regex: "^[A-Z]{1,3}-[A-Z]{1,2}\\d{1,4}$",
  },
  {
    name_uz: "Greece",
    name_ru: "Греция",
    name_tr: "Yunanistan",
    name_zh: "希腊",
    name_en: "Greece",
    code: "GR",
    vehicle_plate_regex: "^[A-Z]{3}-\\d{4}$",
  },
  {
    name_uz: "Hungary",
    name_ru: "Венгрия",
    name_tr: "Macaristan",
    name_zh: "匈牙利",
    name_en: "Hungary",
    code: "HU",
    vehicle_plate_regex: "^[A-Z]{3}-\\d{3}$",
  },
  {
    name_uz: "Iceland",
    name_ru: "Исландия",
    name_tr: "İzlanda",
    name_zh: "冰岛",
    name_en: "Iceland",
    code: "IS",
    vehicle_plate_regex: "^[A-Z]{1,2}\\d{3}$",
  },
  {
    name_uz: "Ireland",
    name_ru: "Ирландия",
    name_tr: "İrlanda",
    name_zh: "爱尔兰",
    name_en: "Ireland",
    code: "IE",
    vehicle_plate_regex: "^d{2}-[A-Z]{1,2}-\\d{1,5}$",
  },
  {
    name_uz: "Italy",
    name_ru: "Италия",
    name_tr: "İtalya",
    name_zh: "意大利",
    name_en: "Italy",
    code: "IT",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}[A-Z]{2}$",
  },
  {
    name_uz: "Latvia",
    name_ru: "Латвия",
    name_tr: "Letonya",
    name_zh: "拉脱维亚",
    name_en: "Latvia",
    code: "LV",
    vehicle_plate_regex: "^[A-Z]{2}-\\d{4}$",
  },
  {
    name_uz: "Liechtenstein",
    name_ru: "Лихтенштейн",
    name_tr: "Lihtenştayn",
    name_zh: "列支敦士登",
    name_en: "Liechtenstein",
    code: "LI",
    vehicle_plate_regex: "^FL-\\d{1,5}$",
  },
  {
    name_uz: "Lithuania",
    name_ru: "Литва",
    name_tr: "Litvanya",
    name_zh: "立陶宛",
    name_en: "Lithuania",
    code: "LT",
    vehicle_plate_regex: "^[A-Z]{3}\\d{3}$",
  },
  {
    name_uz: "Luxembourg",
    name_ru: "Люксембург",
    name_tr: "Lüksemburg",
    name_zh: "卢森堡",
    name_en: "Luxembourg",
    code: "LU",
    vehicle_plate_regex: "^[A-Z]{2}-\\d{5}$",
  },
  {
    name_uz: "Malta",
    name_ru: "Мальта",
    name_tr: "Malta",
    name_zh: "马耳他",
    name_en: "Malta",
    code: "MT",
    vehicle_plate_regex: "^[A-Z]{3}\\d{4}$",
  },
  {
    name_uz: "Netherlands",
    name_ru: "Нидерланды",
    name_tr: "Hollanda",
    name_zh: "荷兰",
    name_en: "Netherlands",
    code: "NL",
    vehicle_plate_regex: "^[A-Z]{1,2}\\d{2,3}[A-Z]{1,2}$",
  },
  {
    name_uz: "North Macedonia",
    name_ru: "Северная Македония",
    name_tr: "Kuzey Makedonya",
    name_zh: "北马其顿",
    name_en: "North Macedonia",
    code: "MK",
    vehicle_plate_regex: "^[A-Z]{2}\\d{1,4}[A-Z]{1,2}$",
  },
  {
    name_uz: "Norway",
    name_ru: "Норвегия",
    name_tr: "Norveç",
    name_zh: "挪威",
    name_en: "Norway",
    code: "NO",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3,4}$",
  },
  {
    name_uz: "Poland",
    name_ru: "Польша",
    name_tr: "Polonya",
    name_zh: "波兰",
    name_en: "Poland",
    code: "PL",
    vehicle_plate_regex: "^[A-Z]{2}\\d{4}[A-Z]{1}$",
  },
  {
    name_uz: "Portugal",
    name_ru: "Португалия",
    name_tr: "Portekiz",
    name_zh: "葡萄牙",
    name_en: "Portugal",
    code: "PT",
    vehicle_plate_regex: "^[A-Z]{2}\\d{2}-\\d{2}$",
  },
  {
    name_uz: "Romania",
    name_ru: "Румыния",
    name_tr: "Romanya",
    name_zh: "罗马尼亚",
    name_en: "Romania",
    code: "RO",
    vehicle_plate_regex: "^[B-DFGHJKLMNPRSTVWXYZ]{2}\\d{2,4}[A-Z]{2}$",
  },
  {
    name_uz: "San Marino",
    name_ru: "Сан-Марино",
    name_tr: "San Marino",
    name_zh: "圣马力诺",
    name_en: "San Marino",
    code: "SM",
    vehicle_plate_regex: "^[A-Z]{1,2}\\d{1,5}$",
  },
  {
    name_uz: "Serbia",
    name_ru: "Сербия",
    name_tr: "Sırbistan",
    name_zh: "塞尔维亚",
    name_en: "Serbia",
    code: "RS",
    vehicle_plate_regex: "^[A-Z]{2}\\d{1,4}$",
  },
  {
    name_uz: "Slovakia",
    name_ru: "Словакия",
    name_tr: "Slovakya",
    name_zh: "斯洛伐克",
    name_en: "Slovakia",
    code: "SK",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}[A-Z]{1}$",
  },
  {
    name_uz: "Slovenia",
    name_ru: "Словения",
    name_tr: "Slovenya",
    name_zh: "斯洛文尼亚",
    name_en: "Slovenia",
    code: "SI",
    vehicle_plate_regex: "^[A-Z]{2}\\d{3}[A-Z]{1,2}$",
  },
  {
    name_uz: "Spain",
    name_ru: "Испания",
    name_tr: "İspanya",
    name_zh: "西班牙",
    name_en: "Spain",
    code: "ES",
    vehicle_plate_regex: "^[A-Z]{4}\\d{3}$",
  },
  {
    name_uz: "Sweden",
    name_ru: "Швеция",
    name_tr: "İsveç",
    name_zh: "瑞典",
    name_en: "Sweden",
    code: "SE",
    vehicle_plate_regex: "^[A-Z]{3}\\d{3}$",
  },
  {
    name_uz: "Switzerland",
    name_ru: "Швейцария",
    name_tr: "İsviçre",
    name_zh: "瑞士",
    name_en: "Switzerland",
    code: "CH",
    vehicle_plate_regex: "^[A-Z]{2}\\d{1,3}$",
  },
  {
    name_uz: "Turkey",
    name_ru: "Турция",
    name_tr: "Türkiye",
    name_zh: "土耳其",
    name_en: "Turkey",
    code: "TR",
    vehicle_plate_regex: "^[0-9]{2}[A-Z]{1,2}\\d{1,4}$",
  },
  {
    name_uz: "United Kingdom",
    name_ru: "Великобритания",
    name_tr: "Birleşik Krallık",
    name_zh: "英国",
    name_en: "United Kingdom",
    code: "GB",
    vehicle_plate_regex: "^[A-Z]{2}\\d{1,4}[A-Z]{1}$",
  },
  {
    name_uz: "Vatican City",
    name_ru: "Ватикан",
    name_tr: "Vatikan",
    name_zh: "梵蒂冈",
    name_en: "Vatican City",
    code: "VA",
    vehicle_plate_regex: "^[A-Z]{1,2}\\d{1,5}$",
  },
  {
    name_uz: "China",
    name_ru: "Китай",
    name_tr: "Çin",
    name_zh: "中国",
    name_en: "China",
    code: "CN",
    vehicle_plate_regex: "^[A-Z]{1}[A-Z\\d]{5}$",
  },
  {
    name_uz: "India",
    name_ru: "Индия",
    name_tr: "Hindistan",
    name_zh: "印度",
    name_en: "India",
    code: "IN",
    vehicle_plate_regex: "^[A-Z]{2}\\d{4}$",
  },
  {
    name_uz: "Monaco",
    name_ru: "Монако",
    name_tr: "Monako",
    name_zh: "摩纳哥",
    name_en: "Monaco",
    code: "MC",
    vehicle_plate_regex: "^[A-Z]{1,3}\\d{1,5}$",
  }
];
